2025-05-26 14:57:37	Logger	DEBUG	main.py:183	Path /docs is public. Skipping authentication.
2025-05-26 14:57:37	Logger	DEBUG	main.py:183	Path /openapi.json is public. Skipping authentication.
2025-05-26 14:58:47	Logger	DEBUG	main.py:183	Path /docs is public. Skipping authentication.
2025-05-26 14:58:47	Logger	DEBUG	main.py:183	Path /openapi.json is public. Skipping authentication.
2025-05-26 14:59:04	Logger	WARNING	main.py:255	No valid tokens found for path /account/self. Unauthorized access attempt.
2025-05-26 15:19:33	Logger	DEBUG	main.py:222	Path /docs is public. Skipping authentication.
2025-05-26 15:19:33	Logger	DEBUG	main.py:222	Path /openapi.json is public. Skipping authentication.
2025-05-26 15:19:36	Logger	WARNING	main.py:276	No valid tokens found for path /account/self. Unauthorized access attempt.
2025-05-26 15:22:58	Logger	DEBUG	main.py:222	Path /docs is public. Skipping authentication.
2025-05-26 15:22:59	Logger	DEBUG	main.py:222	Path /openapi.json is public. Skipping authentication.
2025-05-26 15:23:01	Logger	WARNING	main.py:276	No valid tokens found for path /account/self. Unauthorized access attempt.
2025-05-26 15:26:30	Logger	DEBUG	main.py:222	Path /docs is public. Skipping authentication.
2025-05-26 15:26:31	Logger	DEBUG	main.py:222	Path /openapi.json is public. Skipping authentication.
2025-05-26 15:26:33	Logger	WARNING	main.py:276	No valid tokens found for path /account/self. Unauthorized access attempt.
2025-05-26 15:37:46	Logger	DEBUG	main.py:226	Path /docs is public. Skipping authentication.
2025-05-26 15:37:46	Logger	DEBUG	main.py:226	Path /openapi.json is public. Skipping authentication.
2025-05-26 15:37:49	Logger	DEBUG	main.py:226	Path /docs is public. Skipping authentication.
2025-05-26 15:37:50	Logger	DEBUG	main.py:226	Path /openapi.json is public. Skipping authentication.
2025-05-26 15:37:52	Logger	WARNING	main.py:304	No valid tokens found for path /account/self. Unauthorized access attempt.
2025-05-26 15:38:29	Logger	DEBUG	main.py:221	Path /auth/login/user is for unauthenticated users. Proceeding.
2025-05-26 15:38:30	Logger	INFO	UserService.py:33	User fetched by username: string
2025-05-26 15:38:36	Logger	INFO	UserService.py:42	User fetched by ID: 2
2025-05-26 17:23:44	Logger	DEBUG	main.py:236	Path /docs is public. Skipping authentication.
2025-05-26 17:23:45	Logger	DEBUG	main.py:236	Path /openapi.json is public. Skipping authentication.
2025-05-26 17:24:01	Logger	INFO	UserService.py:42	User fetched by ID: 2
2025-05-26 17:24:25	Logger	DEBUG	main.py:249	Authenticated user attempting to access authenticated path /account/self/update.
2025-05-26 17:25:59	Logger	DEBUG	main.py:236	Path /docs is public. Skipping authentication.
2025-05-26 17:25:59	Logger	DEBUG	main.py:236	Path /openapi.json is public. Skipping authentication.
2025-05-26 17:26:04	Logger	DEBUG	main.py:249	Authenticated user attempting to access authenticated path /account/self/update.
2025-05-26 17:26:05	Logger	INFO	UserService.py:91	User with ID 2 successfully updated. Changed fields: ['name', 'username', 'email', 'hashed_password']
2025-05-26 17:26:10	Logger	INFO	UserService.py:42	User fetched by ID: 2
2025-05-26 17:26:23	Logger	DEBUG	main.py:249	Authenticated user attempting to access authenticated path /account/self/update.
2025-05-26 17:26:24	Logger	INFO	UserService.py:91	User with ID 2 successfully updated. Changed fields: ['name', 'username', 'email', 'hashed_password']
2025-05-26 17:26:27	Logger	INFO	UserService.py:42	User fetched by ID: 2
2025-05-26 17:26:51	Logger	DEBUG	main.py:249	Authenticated user attempting to access authenticated path /account/self/update.
2025-05-26 17:26:51	Logger	INFO	UserService.py:91	User with ID 2 successfully updated. Changed fields: ['name', 'username', 'email', 'hashed_password']
2025-05-26 17:26:55	Logger	INFO	UserService.py:42	User fetched by ID: 2
2025-05-26 17:27:07	Logger	DEBUG	main.py:249	Authenticated user attempting to access authenticated path /account/self/update.
2025-05-26 17:27:07	Logger	WARNING	UserService.py:57	Incorrect submit password for user ID: 2
2025-05-26 17:27:15	Logger	DEBUG	main.py:249	Authenticated user attempting to access authenticated path /account/self/update.
2025-05-26 17:27:15	Logger	INFO	UserService.py:91	User with ID 2 successfully updated. Changed fields: ['name', 'username', 'email', 'hashed_password']
2025-05-26 17:28:39	Logger	INFO	UserService.py:42	User fetched by ID: 2
